package bean.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import bean.CurrentUser;
import bean.RecommendMusic;

import bean.dao.CurrentUserDao;
import bean.dao.RecommendMusicDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig currentUserDaoConfig;
    private final DaoConfig recommendMusicDaoConfig;

    private final CurrentUserDao currentUserDao;
    private final RecommendMusicDao recommendMusicDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        currentUserDaoConfig = daoConfigMap.get(CurrentUserDao.class).clone();
        currentUserDaoConfig.initIdentityScope(type);

        recommendMusicDaoConfig = daoConfigMap.get(RecommendMusicDao.class).clone();
        recommendMusicDaoConfig.initIdentityScope(type);

        currentUserDao = new CurrentUserDao(currentUserDaoConfig, this);
        recommendMusicDao = new RecommendMusicDao(recommendMusicDaoConfig, this);

        registerDao(CurrentUser.class, currentUserDao);
        registerDao(RecommendMusic.class, recommendMusicDao);
    }

    public void clear() {
        currentUserDaoConfig.clearIdentityScope();
        recommendMusicDaoConfig.clearIdentityScope();
    }

    public CurrentUserDao getCurrentUserDao() {
        return currentUserDao;
    }

    public RecommendMusicDao getRecommendMusicDao() {
        return recommendMusicDao;
    }

}
