package bean.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import bean.RecommendMusic;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RECOMMEND_MUSIC".
*/
public class RecommendMusicDao extends AbstractDao<RecommendMusic, Long> {

    public static final String TABLENAME = "RECOMMEND_MUSIC";

    /**
     * Properties of entity RecommendMusic.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Artist_id = new Property(1, String.class, "artist_id", false, "ARTIST_ID");
        public final static Property Language = new Property(2, String.class, "language", false, "LANGUAGE");
        public final static Property Pic_big = new Property(3, String.class, "pic_big", false, "PIC_BIG");
        public final static Property Pic_small = new Property(4, String.class, "pic_small", false, "PIC_SMALL");
        public final static Property Country = new Property(5, String.class, "country", false, "COUNTRY");
        public final static Property Area = new Property(6, String.class, "area", false, "AREA");
        public final static Property Publishtime = new Property(7, String.class, "publishtime", false, "PUBLISHTIME");
        public final static Property Album_no = new Property(8, String.class, "album_no", false, "ALBUM_NO");
        public final static Property Lrclink = new Property(9, String.class, "lrclink", false, "LRCLINK");
        public final static Property Copy_type = new Property(10, String.class, "copy_type", false, "COPY_TYPE");
        public final static Property Hot = new Property(11, String.class, "hot", false, "HOT");
        public final static Property All_artist_ting_uid = new Property(12, String.class, "all_artist_ting_uid", false, "ALL_ARTIST_TING_UID");
        public final static Property Resource_type = new Property(13, String.class, "resource_type", false, "RESOURCE_TYPE");
        public final static Property Is_new = new Property(14, String.class, "is_new", false, "IS_NEW");
        public final static Property Rank_change = new Property(15, String.class, "rank_change", false, "RANK_CHANGE");
        public final static Property Rank = new Property(16, String.class, "rank", false, "RANK");
        public final static Property All_artist_id = new Property(17, String.class, "all_artist_id", false, "ALL_ARTIST_ID");
        public final static Property Style = new Property(18, String.class, "style", false, "STYLE");
        public final static Property Del_status = new Property(19, String.class, "del_status", false, "DEL_STATUS");
        public final static Property Relate_status = new Property(20, String.class, "relate_status", false, "RELATE_STATUS");
        public final static Property Toneid = new Property(21, String.class, "toneid", false, "TONEID");
        public final static Property All_rate = new Property(22, String.class, "all_rate", false, "ALL_RATE");
        public final static Property File_duration = new Property(23, int.class, "file_duration", false, "FILE_DURATION");
        public final static Property Has_mv_mobile = new Property(24, int.class, "has_mv_mobile", false, "HAS_MV_MOBILE");
        public final static Property Versions = new Property(25, String.class, "versions", false, "VERSIONS");
        public final static Property Bitrate_fee = new Property(26, String.class, "bitrate_fee", false, "BITRATE_FEE");
        public final static Property Biaoshi = new Property(27, String.class, "biaoshi", false, "BIAOSHI");
        public final static Property Info = new Property(28, String.class, "info", false, "INFO");
        public final static Property Has_filmtv = new Property(29, String.class, "has_filmtv", false, "HAS_FILMTV");
        public final static Property Si_proxycompany = new Property(30, String.class, "si_proxycompany", false, "SI_PROXYCOMPANY");
        public final static Property Song_id = new Property(31, String.class, "song_id", false, "SONG_ID");
        public final static Property Title = new Property(32, String.class, "title", false, "TITLE");
        public final static Property Ting_uid = new Property(33, String.class, "ting_uid", false, "TING_UID");
        public final static Property Author = new Property(34, String.class, "author", false, "AUTHOR");
        public final static Property Album_id = new Property(35, String.class, "album_id", false, "ALBUM_ID");
        public final static Property Album_title = new Property(36, String.class, "album_title", false, "ALBUM_TITLE");
        public final static Property Is_first_publish = new Property(37, int.class, "is_first_publish", false, "IS_FIRST_PUBLISH");
        public final static Property Havehigh = new Property(38, int.class, "havehigh", false, "HAVEHIGH");
        public final static Property Charge = new Property(39, int.class, "charge", false, "CHARGE");
        public final static Property Has_mv = new Property(40, int.class, "has_mv", false, "HAS_MV");
        public final static Property Learn = new Property(41, int.class, "learn", false, "LEARN");
        public final static Property Song_source = new Property(42, String.class, "song_source", false, "SONG_SOURCE");
        public final static Property Piao_id = new Property(43, String.class, "piao_id", false, "PIAO_ID");
        public final static Property Korean_bb_song = new Property(44, String.class, "korean_bb_song", false, "KOREAN_BB_SONG");
        public final static Property Resource_type_ext = new Property(45, String.class, "resource_type_ext", false, "RESOURCE_TYPE_EXT");
        public final static Property Mv_provider = new Property(46, String.class, "mv_provider", false, "MV_PROVIDER");
        public final static Property Artist_name = new Property(47, String.class, "artist_name", false, "ARTIST_NAME");
    }


    public RecommendMusicDao(DaoConfig config) {
        super(config);
    }
    
    public RecommendMusicDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RECOMMEND_MUSIC\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ARTIST_ID\" TEXT," + // 1: artist_id
                "\"LANGUAGE\" TEXT," + // 2: language
                "\"PIC_BIG\" TEXT," + // 3: pic_big
                "\"PIC_SMALL\" TEXT," + // 4: pic_small
                "\"COUNTRY\" TEXT," + // 5: country
                "\"AREA\" TEXT," + // 6: area
                "\"PUBLISHTIME\" TEXT," + // 7: publishtime
                "\"ALBUM_NO\" TEXT," + // 8: album_no
                "\"LRCLINK\" TEXT," + // 9: lrclink
                "\"COPY_TYPE\" TEXT," + // 10: copy_type
                "\"HOT\" TEXT," + // 11: hot
                "\"ALL_ARTIST_TING_UID\" TEXT," + // 12: all_artist_ting_uid
                "\"RESOURCE_TYPE\" TEXT," + // 13: resource_type
                "\"IS_NEW\" TEXT," + // 14: is_new
                "\"RANK_CHANGE\" TEXT," + // 15: rank_change
                "\"RANK\" TEXT," + // 16: rank
                "\"ALL_ARTIST_ID\" TEXT," + // 17: all_artist_id
                "\"STYLE\" TEXT," + // 18: style
                "\"DEL_STATUS\" TEXT," + // 19: del_status
                "\"RELATE_STATUS\" TEXT," + // 20: relate_status
                "\"TONEID\" TEXT," + // 21: toneid
                "\"ALL_RATE\" TEXT," + // 22: all_rate
                "\"FILE_DURATION\" INTEGER NOT NULL ," + // 23: file_duration
                "\"HAS_MV_MOBILE\" INTEGER NOT NULL ," + // 24: has_mv_mobile
                "\"VERSIONS\" TEXT," + // 25: versions
                "\"BITRATE_FEE\" TEXT," + // 26: bitrate_fee
                "\"BIAOSHI\" TEXT," + // 27: biaoshi
                "\"INFO\" TEXT," + // 28: info
                "\"HAS_FILMTV\" TEXT," + // 29: has_filmtv
                "\"SI_PROXYCOMPANY\" TEXT," + // 30: si_proxycompany
                "\"SONG_ID\" TEXT," + // 31: song_id
                "\"TITLE\" TEXT," + // 32: title
                "\"TING_UID\" TEXT," + // 33: ting_uid
                "\"AUTHOR\" TEXT," + // 34: author
                "\"ALBUM_ID\" TEXT," + // 35: album_id
                "\"ALBUM_TITLE\" TEXT," + // 36: album_title
                "\"IS_FIRST_PUBLISH\" INTEGER NOT NULL ," + // 37: is_first_publish
                "\"HAVEHIGH\" INTEGER NOT NULL ," + // 38: havehigh
                "\"CHARGE\" INTEGER NOT NULL ," + // 39: charge
                "\"HAS_MV\" INTEGER NOT NULL ," + // 40: has_mv
                "\"LEARN\" INTEGER NOT NULL ," + // 41: learn
                "\"SONG_SOURCE\" TEXT," + // 42: song_source
                "\"PIAO_ID\" TEXT," + // 43: piao_id
                "\"KOREAN_BB_SONG\" TEXT," + // 44: korean_bb_song
                "\"RESOURCE_TYPE_EXT\" TEXT," + // 45: resource_type_ext
                "\"MV_PROVIDER\" TEXT," + // 46: mv_provider
                "\"ARTIST_NAME\" TEXT);"); // 47: artist_name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RECOMMEND_MUSIC\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RecommendMusic entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String artist_id = entity.getArtist_id();
        if (artist_id != null) {
            stmt.bindString(2, artist_id);
        }
 
        String language = entity.getLanguage();
        if (language != null) {
            stmt.bindString(3, language);
        }
 
        String pic_big = entity.getPic_big();
        if (pic_big != null) {
            stmt.bindString(4, pic_big);
        }
 
        String pic_small = entity.getPic_small();
        if (pic_small != null) {
            stmt.bindString(5, pic_small);
        }
 
        String country = entity.getCountry();
        if (country != null) {
            stmt.bindString(6, country);
        }
 
        String area = entity.getArea();
        if (area != null) {
            stmt.bindString(7, area);
        }
 
        String publishtime = entity.getPublishtime();
        if (publishtime != null) {
            stmt.bindString(8, publishtime);
        }
 
        String album_no = entity.getAlbum_no();
        if (album_no != null) {
            stmt.bindString(9, album_no);
        }
 
        String lrclink = entity.getLrclink();
        if (lrclink != null) {
            stmt.bindString(10, lrclink);
        }
 
        String copy_type = entity.getCopy_type();
        if (copy_type != null) {
            stmt.bindString(11, copy_type);
        }
 
        String hot = entity.getHot();
        if (hot != null) {
            stmt.bindString(12, hot);
        }
 
        String all_artist_ting_uid = entity.getAll_artist_ting_uid();
        if (all_artist_ting_uid != null) {
            stmt.bindString(13, all_artist_ting_uid);
        }
 
        String resource_type = entity.getResource_type();
        if (resource_type != null) {
            stmt.bindString(14, resource_type);
        }
 
        String is_new = entity.getIs_new();
        if (is_new != null) {
            stmt.bindString(15, is_new);
        }
 
        String rank_change = entity.getRank_change();
        if (rank_change != null) {
            stmt.bindString(16, rank_change);
        }
 
        String rank = entity.getRank();
        if (rank != null) {
            stmt.bindString(17, rank);
        }
 
        String all_artist_id = entity.getAll_artist_id();
        if (all_artist_id != null) {
            stmt.bindString(18, all_artist_id);
        }
 
        String style = entity.getStyle();
        if (style != null) {
            stmt.bindString(19, style);
        }
 
        String del_status = entity.getDel_status();
        if (del_status != null) {
            stmt.bindString(20, del_status);
        }
 
        String relate_status = entity.getRelate_status();
        if (relate_status != null) {
            stmt.bindString(21, relate_status);
        }
 
        String toneid = entity.getToneid();
        if (toneid != null) {
            stmt.bindString(22, toneid);
        }
 
        String all_rate = entity.getAll_rate();
        if (all_rate != null) {
            stmt.bindString(23, all_rate);
        }
        stmt.bindLong(24, entity.getFile_duration());
        stmt.bindLong(25, entity.getHas_mv_mobile());
 
        String versions = entity.getVersions();
        if (versions != null) {
            stmt.bindString(26, versions);
        }
 
        String bitrate_fee = entity.getBitrate_fee();
        if (bitrate_fee != null) {
            stmt.bindString(27, bitrate_fee);
        }
 
        String biaoshi = entity.getBiaoshi();
        if (biaoshi != null) {
            stmt.bindString(28, biaoshi);
        }
 
        String info = entity.getInfo();
        if (info != null) {
            stmt.bindString(29, info);
        }
 
        String has_filmtv = entity.getHas_filmtv();
        if (has_filmtv != null) {
            stmt.bindString(30, has_filmtv);
        }
 
        String si_proxycompany = entity.getSi_proxycompany();
        if (si_proxycompany != null) {
            stmt.bindString(31, si_proxycompany);
        }
 
        String song_id = entity.getSong_id();
        if (song_id != null) {
            stmt.bindString(32, song_id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(33, title);
        }
 
        String ting_uid = entity.getTing_uid();
        if (ting_uid != null) {
            stmt.bindString(34, ting_uid);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(35, author);
        }
 
        String album_id = entity.getAlbum_id();
        if (album_id != null) {
            stmt.bindString(36, album_id);
        }
 
        String album_title = entity.getAlbum_title();
        if (album_title != null) {
            stmt.bindString(37, album_title);
        }
        stmt.bindLong(38, entity.getIs_first_publish());
        stmt.bindLong(39, entity.getHavehigh());
        stmt.bindLong(40, entity.getCharge());
        stmt.bindLong(41, entity.getHas_mv());
        stmt.bindLong(42, entity.getLearn());
 
        String song_source = entity.getSong_source();
        if (song_source != null) {
            stmt.bindString(43, song_source);
        }
 
        String piao_id = entity.getPiao_id();
        if (piao_id != null) {
            stmt.bindString(44, piao_id);
        }
 
        String korean_bb_song = entity.getKorean_bb_song();
        if (korean_bb_song != null) {
            stmt.bindString(45, korean_bb_song);
        }
 
        String resource_type_ext = entity.getResource_type_ext();
        if (resource_type_ext != null) {
            stmt.bindString(46, resource_type_ext);
        }
 
        String mv_provider = entity.getMv_provider();
        if (mv_provider != null) {
            stmt.bindString(47, mv_provider);
        }
 
        String artist_name = entity.getArtist_name();
        if (artist_name != null) {
            stmt.bindString(48, artist_name);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RecommendMusic entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String artist_id = entity.getArtist_id();
        if (artist_id != null) {
            stmt.bindString(2, artist_id);
        }
 
        String language = entity.getLanguage();
        if (language != null) {
            stmt.bindString(3, language);
        }
 
        String pic_big = entity.getPic_big();
        if (pic_big != null) {
            stmt.bindString(4, pic_big);
        }
 
        String pic_small = entity.getPic_small();
        if (pic_small != null) {
            stmt.bindString(5, pic_small);
        }
 
        String country = entity.getCountry();
        if (country != null) {
            stmt.bindString(6, country);
        }
 
        String area = entity.getArea();
        if (area != null) {
            stmt.bindString(7, area);
        }
 
        String publishtime = entity.getPublishtime();
        if (publishtime != null) {
            stmt.bindString(8, publishtime);
        }
 
        String album_no = entity.getAlbum_no();
        if (album_no != null) {
            stmt.bindString(9, album_no);
        }
 
        String lrclink = entity.getLrclink();
        if (lrclink != null) {
            stmt.bindString(10, lrclink);
        }
 
        String copy_type = entity.getCopy_type();
        if (copy_type != null) {
            stmt.bindString(11, copy_type);
        }
 
        String hot = entity.getHot();
        if (hot != null) {
            stmt.bindString(12, hot);
        }
 
        String all_artist_ting_uid = entity.getAll_artist_ting_uid();
        if (all_artist_ting_uid != null) {
            stmt.bindString(13, all_artist_ting_uid);
        }
 
        String resource_type = entity.getResource_type();
        if (resource_type != null) {
            stmt.bindString(14, resource_type);
        }
 
        String is_new = entity.getIs_new();
        if (is_new != null) {
            stmt.bindString(15, is_new);
        }
 
        String rank_change = entity.getRank_change();
        if (rank_change != null) {
            stmt.bindString(16, rank_change);
        }
 
        String rank = entity.getRank();
        if (rank != null) {
            stmt.bindString(17, rank);
        }
 
        String all_artist_id = entity.getAll_artist_id();
        if (all_artist_id != null) {
            stmt.bindString(18, all_artist_id);
        }
 
        String style = entity.getStyle();
        if (style != null) {
            stmt.bindString(19, style);
        }
 
        String del_status = entity.getDel_status();
        if (del_status != null) {
            stmt.bindString(20, del_status);
        }
 
        String relate_status = entity.getRelate_status();
        if (relate_status != null) {
            stmt.bindString(21, relate_status);
        }
 
        String toneid = entity.getToneid();
        if (toneid != null) {
            stmt.bindString(22, toneid);
        }
 
        String all_rate = entity.getAll_rate();
        if (all_rate != null) {
            stmt.bindString(23, all_rate);
        }
        stmt.bindLong(24, entity.getFile_duration());
        stmt.bindLong(25, entity.getHas_mv_mobile());
 
        String versions = entity.getVersions();
        if (versions != null) {
            stmt.bindString(26, versions);
        }
 
        String bitrate_fee = entity.getBitrate_fee();
        if (bitrate_fee != null) {
            stmt.bindString(27, bitrate_fee);
        }
 
        String biaoshi = entity.getBiaoshi();
        if (biaoshi != null) {
            stmt.bindString(28, biaoshi);
        }
 
        String info = entity.getInfo();
        if (info != null) {
            stmt.bindString(29, info);
        }
 
        String has_filmtv = entity.getHas_filmtv();
        if (has_filmtv != null) {
            stmt.bindString(30, has_filmtv);
        }
 
        String si_proxycompany = entity.getSi_proxycompany();
        if (si_proxycompany != null) {
            stmt.bindString(31, si_proxycompany);
        }
 
        String song_id = entity.getSong_id();
        if (song_id != null) {
            stmt.bindString(32, song_id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(33, title);
        }
 
        String ting_uid = entity.getTing_uid();
        if (ting_uid != null) {
            stmt.bindString(34, ting_uid);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(35, author);
        }
 
        String album_id = entity.getAlbum_id();
        if (album_id != null) {
            stmt.bindString(36, album_id);
        }
 
        String album_title = entity.getAlbum_title();
        if (album_title != null) {
            stmt.bindString(37, album_title);
        }
        stmt.bindLong(38, entity.getIs_first_publish());
        stmt.bindLong(39, entity.getHavehigh());
        stmt.bindLong(40, entity.getCharge());
        stmt.bindLong(41, entity.getHas_mv());
        stmt.bindLong(42, entity.getLearn());
 
        String song_source = entity.getSong_source();
        if (song_source != null) {
            stmt.bindString(43, song_source);
        }
 
        String piao_id = entity.getPiao_id();
        if (piao_id != null) {
            stmt.bindString(44, piao_id);
        }
 
        String korean_bb_song = entity.getKorean_bb_song();
        if (korean_bb_song != null) {
            stmt.bindString(45, korean_bb_song);
        }
 
        String resource_type_ext = entity.getResource_type_ext();
        if (resource_type_ext != null) {
            stmt.bindString(46, resource_type_ext);
        }
 
        String mv_provider = entity.getMv_provider();
        if (mv_provider != null) {
            stmt.bindString(47, mv_provider);
        }
 
        String artist_name = entity.getArtist_name();
        if (artist_name != null) {
            stmt.bindString(48, artist_name);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public RecommendMusic readEntity(Cursor cursor, int offset) {
        RecommendMusic entity = new RecommendMusic( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // artist_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // language
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // pic_big
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // pic_small
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // country
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // area
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // publishtime
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // album_no
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // lrclink
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // copy_type
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // hot
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // all_artist_ting_uid
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // resource_type
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // is_new
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // rank_change
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // rank
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // all_artist_id
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // style
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // del_status
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // relate_status
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // toneid
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // all_rate
            cursor.getInt(offset + 23), // file_duration
            cursor.getInt(offset + 24), // has_mv_mobile
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // versions
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // bitrate_fee
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // biaoshi
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // info
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // has_filmtv
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // si_proxycompany
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // song_id
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // title
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // ting_uid
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // author
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // album_id
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // album_title
            cursor.getInt(offset + 37), // is_first_publish
            cursor.getInt(offset + 38), // havehigh
            cursor.getInt(offset + 39), // charge
            cursor.getInt(offset + 40), // has_mv
            cursor.getInt(offset + 41), // learn
            cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42), // song_source
            cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43), // piao_id
            cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44), // korean_bb_song
            cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45), // resource_type_ext
            cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46), // mv_provider
            cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47) // artist_name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RecommendMusic entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setArtist_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLanguage(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPic_big(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPic_small(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCountry(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setArea(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPublishtime(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setAlbum_no(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setLrclink(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setCopy_type(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setHot(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setAll_artist_ting_uid(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setResource_type(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setIs_new(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setRank_change(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setRank(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setAll_artist_id(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setStyle(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setDel_status(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setRelate_status(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setToneid(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setAll_rate(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setFile_duration(cursor.getInt(offset + 23));
        entity.setHas_mv_mobile(cursor.getInt(offset + 24));
        entity.setVersions(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setBitrate_fee(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setBiaoshi(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setInfo(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setHas_filmtv(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setSi_proxycompany(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setSong_id(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setTitle(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setTing_uid(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setAuthor(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setAlbum_id(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setAlbum_title(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setIs_first_publish(cursor.getInt(offset + 37));
        entity.setHavehigh(cursor.getInt(offset + 38));
        entity.setCharge(cursor.getInt(offset + 39));
        entity.setHas_mv(cursor.getInt(offset + 40));
        entity.setLearn(cursor.getInt(offset + 41));
        entity.setSong_source(cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42));
        entity.setPiao_id(cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43));
        entity.setKorean_bb_song(cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44));
        entity.setResource_type_ext(cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45));
        entity.setMv_provider(cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46));
        entity.setArtist_name(cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RecommendMusic entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RecommendMusic entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RecommendMusic entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
